use_frameworks!

target 'CHTools_Example' do
  pod 'CHTools', :path => '../'

  target 'CHTools_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
